---
- import_tasks: tasks/tools.yml
  when: configure_tools
  tags: ['tools']

- import_tasks: tasks/terminal.yml
  when: configure_terminal
  tags: ['terminal']

- import_tasks: tasks/osx.yml
  when: configure_osx and ansible_distribution == 'MacOSX'
  tags: ['osx']

- import_tasks: tasks/extra-packages.yml
  tags: ['extra-packages']
