---

- name: Install tools (apt)
  become: true
  apt:
    name: "{{ item }}"
    state: "latest"
    update_cache: true
  loop:
    - neofetch
    - vim
    - htop
    - tmux
    - git
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Raspbian' or ansible_distribution == 'Armbian' 
