---

configure_tools: true
configure_terminal: true
configure_osx: false
configure_swap: true
configure_network: true
configure_cgroup: true
configure_containerd: true
configure_kubernetes: true
configure_zram: true
configure_tmux_dashboard: true
configure_nginx: true
configure_haproxy: true
configure_keepalived: true
configure_node_tags: false

osx_script: "~/.osx --no-restart"

omz_git_repository: "https://github.com/robbyrussell/oh-my-zsh.git"
omz_install_directory: ".oh-my-zsh"

containerd_config_cgroup_driver_systemd: true

kubernetes_cluster_address: mamut.cluster.kube.zebardy.net

kubernetes_version: '1.25'
#kubernetes_kubelet_extra_args: --fail-swap-on=false --system-reserved="cpu=100m,memory=100Mi" --kube-reserved="cpu=100m,memory=100Mi"
kubernetes_config_kubelet_configuration:
  failSwapOn: false
  systemReserved: 
    cpu: 100m
    memory: 100Mi
  kubeReserved: 
    cpu: 100m
    memory: 100Mi

kubernetes_config_cluster_configuration:
  networking:
    podSubnet: "{{ kubernetes_pod_network.cidr }}"
  kubernetesVersion: "{{ kubernetes_version_kubeadm }}"
  controlPlaneEndpoint: "{{ kubernetes_cluster_address }}:8443"

 # etcd:
 #   local:
 #     serverCertSANs:
 #     - "192.168.1.71"
 #     peerCertSANs:
 #     - "192.168.1.71"
 #     extraArgs:
 #       initial-cluster: cluster-node-purple=https://192.168.1.71:2380
 #       listen-peer-urls: https://192.168.1.71:2380
 #       listen-client-urls: https://127.0.0.1:2379
 #       advertise-client-urls: https://127.0.0.1:2379
 #       initial-advertise-peer-urls: https://192.168.1.71:2380
 # apiServer:
 #   extraArgs:
 #     etcd-servers: https://127.0.0.1:2379
  
    

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A
