---
- hosts: cluster

  vars_files:
    - config.yml

  pre_tasks:
  #  - name: Set the master node IP.
  #    set_fact:
  #      kubernetes_master_ip: "{{ hostvars['cluster-node-grey']['ansible_host'] }}"
  #    tags: ['always']
  #    when: configure_kubernetes

    - import_tasks: tasks/swap_off.yml
      become: true
      when: 
        - ansible_swaptotal_mb > 0
        - not node_swap
        - configure_swap
      tags: ['swap']

    - import_tasks: tasks/zram.yml
      become: true
      when: 
        - node_zram
        - configure_zram
      tags: ['zram']

    - import_tasks: tasks/network.yml
      become: true
      when: configure_network
      tags: ['network']

    - import_tasks: tasks/cgroup.yml
      become: true
      when: configure_cgroup
      tags: ['cgroup']

    - import_tasks: tasks/nginx.yml
      become: true
      when: configure_nginx and kubernetes_role == "control_plane"
      tags: ['nginx']

    - import_tasks: tasks/haproxy.yml
      become: true
      when: configure_haproxy and kubernetes_role == "control_plane"
      tags: ['haproxy']

    - import_tasks: tasks/keepalived.yml
      become: true
      when: configure_keepalived and kubernetes_role == "control_plane"
      tags: ['keepalived']

    - import_tasks: tasks/clean_kubernetes.yml
      become: true
      when: configure_clean_kubernetes
      tags: ['clean_kubernetes']

  roles:
    - role: zebardy.dotfiles
      tags: ['dotfiles']

    - role: geerlingguy.containerd
      when: configure_containerd
      become: true
      tags: ['containerd']

    - role: zebardy.kubernetes
      when: configure_kubernetes
      become: true
      tags: ['kubernetes']

  tasks:
    - import_tasks: tasks/tmux_dashboard.yml
      when: configure_tmux_dashboard
      tags: ['tmux_dashboard']

    - import_tasks: tasks/helm.yml
      when: configure_helm and kubernetes_role == 'control_plane'
      become: true
      tags: ['helm']

    - import_tasks: tasks/traefik.yml
      when: configure_traefik and kubernetes_role == 'control_plane'
      run_once: true
      become: true
      tags: ['traefik']

    - import_tasks: tasks/node_tags.yml
      when: configure_node_tags
      become: true
      tags: ['node_tags']

    - import_tasks: tasks/openebs.yml
      when: configure_openebs
      run_once: true
      become: true
      tags: ['openebs']


# kubectl label nodes {{ inventory_hostname }} node=openebs
# kubectl label nodes {{ inventory_hostname }} openebs.io/storage=true
# kubectl label nodes {{ inventory_hostname }} topology.kubernetes.io/zone=[zone]

# sudo apt install hwinfo
# sudo apt install open-iscsi