---
- name: zebardy.dotfiles
  src: https://github.com/zebardy/ansible-dotfiles.git
  version: main
  scm: git

- src: geerlingguy.containerd
- name: zebardy.kubernetes
  src: https://github.com/zebardy/ansible-role-kubernetes.git
  version: master
  scm: git
