---
- name: Install haproxy.
  become: true
  apt:
    name: "haproxy"
    state: "latest"
    update_cache: true

- name: Configure haproxy.
  become: true
  template:
    src: ./files/haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '644'

- name: Restart haproxy.
  become: true
  shell:
    cmd: service haproxy restart

