---
- name: Prepare apt keyring directory.
  ansible.builtin.file:
    path: "/etc/apt/keyrings/}"
    state: directory
    mode: 0755

- name: Get helm apt key.
  ansible.builtin.get_url:
    url: "https://baltocdn.com/helm/signing.asc"
    dest: "/etc/apt/keyrings/helm-apt-keyring.asc"
    mode: '0644'
    force: true

- name: Add helm repository.
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/helm-apt-keyring.asc] https://baltocdn.com/helm/stable/debian/ all main"
    filename: pkgs_helm
    state: present
    update_cache: true

- name: Install helm.
  apt:
    name: "helm"
    state: "latest"
    update_cache: true

- name: Install python yaml.
  apt:
    name: "python3-yaml"
    state: "latest"
    update_cache: true