---
- name: Install keepalived.
  become: true
  apt:
    name: "keepalived"
    state: "latest"
    update_cache: true

- name: Install dnsutils.
  become: true
  apt:
    name: "dnsutils"
    state: "latest"
    update_cache: true

- name: Get IP from hostname.
  shell:
    cmd: "dig {{ kubernetes_cluster_address }} +search +short"
  register: cluster_ip

#- name: Set cluster_ip.
#  set_fact:
#    cluster_ip: "{{ kubernetes_apiserver_advertise_address }}"
  
- name: Configure keepalived.
  become: true
  template:
    src: ./files/keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '644'

- name: Copy check script.
  become: true
  template:
    src: ./files/check_apiserver.j2
    dest: /etc/keepalived/check_apiserver.sh
    mode: '755'

- name: restart services.
  become: true
  shell:
    cmd: service keepalived restart
