---
- name: Install dependencies.
  apt:
    name:
    - jq
    - open-iscsi
    state: "latest"
    update_cache: true

- name: Add longhorn repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"
    
- name: Deploy longhorn.
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: true
    values: 
      global:
        cattle:
          windowsCluster:
            nodeSelector:
              node: storage
            tolerations:
            - effect: NoSchedule
              key: role
              operator: Equal
              value: storage
            - effect: NoExecute
              key: role
              operator: Equal
              value: storage
            defaultSetting:
              taintToleration:
              - effect: NoSchedule
                key: role
                operator: Equal
                value: storage
              - effect: NoExecute
                key: role
                operator: Equal
                value: storage
              systemManagedComponentsNodeSelector:
                node: storage
      persistance:
        defaultNodeSelector:
          enable:
          selector:
            node: storage
      defaultSettings:
        stemManagedComponentsNodeSelector:
          node: storage
        taintToleration:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: storage
        - effect: NoExecute
          key: role
          operator: Equal
          value: storage
      longhornManager:
        nodeSelector:
          node: storage
        tolerations:        
        - effect: NoSchedule
          key: role
          operator: Equal
          value: storage
        - effect: NoExecute
          key: role
          operator: Equal
          value: storage
      longhornUI:
        nodeSelector:
          node: storage
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: storage
        - effect: NoExecute
          key: role
          operator: Equal
          value: storage
      