---
- name: Dissable IPv6.
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.ipv6.conf.eth0.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

# See: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: Ensure procps is installed.
  package:
    name: procps
    state: present

- name: Enable the br_netfilter module.
  modprobe:
    name: br_netfilter
    state: present

- name: Configure modules to load at boot.
  shell: >
    echo "br_netfilter" | sudo tee /etc/modules-load.d/k8s.conf


- name: Let iptables see bridged traffic.
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.ipv4.ip_forward
