---
- name: Check for zram
  become: true
  shell:
    cmd: sudo cat /proc/swaps | grep -i zram
  ignore_errors: true
  register: zram_state

- name: Install zram-tools.
  become: true
  apt:
    name: "zram-tools"
    state: "latest"
    update_cache: true
  when:
    - not zram_state.rc == 0

- name: Configure zram algorithm.
  become: true
  lineinfile:
    path: /etc/default/zramswap
    state: present
    regexp: '^ALGO='
    line: ALGO=lz4
  when:
    - not zram_state.rc == 0

- name: Configure zram percent.
  become: true
  lineinfile:
    path: /etc/default/zramswap
    state: present
    regexp: '^PERCENT='
    line: PERCENT=50
  when:
    - not zram_state.rc == 0

- name: Reboot.
  become: true
  shell:
    cmd: sleep 5 && reboot
  async: 1
  poll: 0
  when:
    - not zram_state.rc == 0

- name: Wait for the reboot to complete.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when:
    - not zram_state.rc == 0

- name: Set memory cache pressure.
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    state: present
    regexp: '^vm.vfs_cache_pressure'
    line: vm.vfs_cache_pressure=500

- name: Set swappiness.
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    state: present
    regexp: '^vm.swappiness'
    line: vm.swappiness=100

- name: Set dirty background ratio.
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    state: present
    regexp: '^vm.dirty_background_ratio'
    line: vm.dirty_background_ratio=1

- name: Set dirty ratio.
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    state: present
    regexp: '^vm.dirty_ratio'
    line: vm.dirty_ratio=50

- name: Ename sysctl settings.
  become: true
  shell:
    cmd: sudo sysctl --system
